cursor #755085
cursor_text_color #755085

foreground #e9e0e7
background #161217

selection_foreground #392c3e
selection_background #d4c0d8

url_color #e3b7f4

color0  #1e1a1f
color8  #231e23

color1  #ffb4ab
color9  #93000a

color2  #e3b7f4
color10 #f6d9ff

color3  #f5b7b6
color11 #ffdad9

color4  #e3b7f4
color12 #e3b7f4

color5  #d4c0d8
color13 #f0dcf4

color6  #f5b7b6
color14 #f5b7b6

color7  #e9e0e7
color15 #cec3ce
