cursor #465d91
cursor_text_color #465d91

foreground #e2e2e9
background #121318

selection_foreground #293042
selection_background #bfc6dc

url_color #afc6ff

color0  #1a1b20
color8  #1e1f25

color1  #ffb4ab
color9  #93000a

color2  #afc6ff
color10 #d9e2ff

color3  #dfbbde
color11 #fdd7fb

color4  #afc6ff
color12 #afc6ff

color5  #bfc6dc
color13 #dbe2f9

color6  #dfbbde
color14 #dfbbde

color7  #e2e2e9
color15 #c5c6d0
